# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
permalink:           pretty

# Setup
title:               Belvain's Blog
tagline:             
description:         'Stories about my projects and other random things.'
url:                 http://hkurhinen.github.io
baseurl:             /
paginate:            7

# About/contact
author:
  name:              Heikki Kurhinen
  url:               
  email:             heikki.kurhinen@gmail.com

# Custom vars
version:             2.0

# Social Media
github:				https://github.com/hkurhinen
twitter:			

# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme:
  creator:			Rizky Ariestiyansyah
  codename:			Naringu
  link:             https://github.com/ariestiyansyah/naringu